pipeline {
    agent any
    stages {
        stage('安装') {
            steps {
                sh 'node -v'
                sh 'npm -v'
                sh 'docker -v'
            }
        }
    }
}
